export const mockCategories = [
  { id: 1, name: "Provincial News", slug: "provincial-news", color: "blue", description: "News from the province of Palawan" },
  { id: 2, name: "City News", slug: "city-news", color: "emerald", description: "News from around the city" },
  { id: 3, name: "Puerto Princesa City", slug: "puerto-princesa-city", color: "indigo", description: "Specific updates from the capital" },
  { id: 4, name: "Police Report", slug: "police-report", color: "red", description: "Latest police and crime reports" },
  { id: 5, name: "National News", slug: "national", color: "slate", description: "News from across the Philippines" },
  { id: 6, name: "Feature", slug: "feature", color: "purple", description: "Special features and long-form stories" },
  { id: 7, name: "Press Release", slug: "press-release", color: "gray", description: "Official press releases" },
  { id: 8, name: "Environment", slug: "environment", color: "green", description: "Environmental and conservation news" },
  { id: 9, name: "Column", slug: "column", color: "amber", description: "Columns and recurring sections" },
  { id: 10, name: "Opinion", slug: "opinion", color: "red", description: "Editorials and opinion pieces" },
  { id: 11, name: "Lifestyle", slug: "lifestyle", color: "pink", description: "Health, travel, and lifestyle" },
  { id: 12, name: "Advertise", slug: "advertise", color: "gray", description: "Advertising info" },
  { id: 13, name: "Legal Section", slug: "legal", color: "slate", description: "Legal notices" },
  { id: 14, name: "International News", slug: "international", color: "sky", description: "World news and global updates" },
  { id: 15, name: "Editorial", slug: "editorial", color: "indigo", description: "The Editorial Board's perspectives" },
  { id: 16, name: "Regional News", slug: "regional-news", color: "orange", description: "Updates from across the MIMAROPA region" },
  { id: 17, name: "Youth & Campus", slug: "youth-campus", color: "pink", description: "Campus news and youth-oriented stories" },
  { id: 18, name: "Tourism", slug: "tourism", color: "teal", description: "Explore the beauty and attractions of Palawan" },
  { id: 19, name: "Technology", slug: "technology", color: "blue", description: "Tech news, innovation, and digital trends" },
  { id: 20, name: "Business", slug: "business", color: "emerald", description: "Economic updates and business highlights" },
  { id: 21, name: "Sports", slug: "sports", color: "orange", description: "Local and national sports updates" },
];

export const mockArticles = [
  {
    id: 1,
    title: "Palawan Named World's Best Island for the 7th Consecutive Year",
    slug: "palawan-named-worlds-best-island-seventh-year",
    excerpt: "Travel + Leisure magazine has once again crowned Palawan as the world's best island, cementing its status as a premier global destination.",
    content: `<p>Palawan has once again been crowned the world's best island by Travel + Leisure magazine, marking the seventh consecutive year the Philippine island has claimed the top spot in the prestigious annual reader's survey.</p>
    <p>The island, known for its pristine beaches, crystal-clear waters, and stunning limestone karst formations, continues to captivate travelers from around the globe. This year's recognition comes amid a surge in sustainable tourism initiatives championed by local government units and the Department of Tourism.</p>
    <h2>Record Tourism Numbers</h2>
    <p>The Province of Palawan reported record-breaking tourist arrivals in the first quarter of 2024, with over 450,000 visitors — a 35% increase from the same period last year. Puerto Princesa, the provincial capital, and El Nido have emerged as the top destinations.</p>
    <blockquote><p>"This recognition is not just an award for Palawan — it's a recognition of the Filipino hospitality, our natural heritage, and the commitment of every stakeholder in preserving what makes our island truly world-class."</p><cite>— Governor Victorino Dennis Socrates</cite></blockquote>
    <p>El Nido's Big Lagoon, Small Lagoon, and the Underground River in Puerto Princesa remain the most photographed destinations, drawing millions of social media impressions monthly.</p>
    <h2>Sustainability Efforts</h2>
    <p>Local authorities have implemented strict carrying capacity limits in key tourist sites to balance tourism growth with environmental conservation. The Palawan Council for Sustainable Development (PCSD) continues to enforce regulations that protect the island's biodiversity.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=1200&h=600&fit=crop",
    categoryId: 18,
    categoryName: "Tourism",
    categorySlug: "tourism",
    authorName: "Maria Santos",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    status: "published",
    featured: true,
    breaking: false,
    views: 12450,
    publishedAt: new Date("2024-03-10T08:00:00"),
    tags: ["Palawan", "Tourism", "Travel", "Philippines"],
  },
  {
    id: 2,
    title: "Underground River Expansion Project Gets Green Light from DENR",
    slug: "underground-river-expansion-denr-approval",
    excerpt: "The Department of Environment and Natural Resources has approved a new visitor management system that will allow more tourists while protecting the UNESCO World Heritage Site.",
    content: `<p>The Department of Environment and Natural Resources (DENR) has given the green light to the Puerto Princesa Underground River's expansion project, which aims to improve visitor experience while maintaining strict environmental safeguards.</p>
    <p>The project, estimated at PHP 2.3 billion, includes the construction of new viewing platforms, improved boat docking facilities, and a state-of-the-art visitor center that will feature interactive exhibits about the river's geological history and biodiversity.</p>
    <h2>New Visitor Management System</h2>
    <p>Central to the expansion is a digital visitor management system that will implement real-time monitoring of tourist numbers throughout the cave system. The system uses AI-powered sensors to track environmental conditions and adjust visitor limits accordingly.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800&h=400&fit=crop",
    categoryId: 5,
    categoryName: "Environment",
    categorySlug: "environment",
    authorName: "Jose Reyes",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 8920,
    publishedAt: new Date("2024-03-09T10:30:00"),
    tags: ["Underground River", "DENR", "Environment", "UNESCO"],
  },
  {
    id: 3,
    title: "New Tech Hub to Open in Puerto Princesa, Creating 5,000 Jobs",
    slug: "tech-hub-puerto-princesa-five-thousand-jobs",
    excerpt: "A major Philippine IT company has announced plans to establish a technology hub in Puerto Princesa City, signaling a new era of digital economy in Palawan.",
    content: `<p>Ayala Corporation's technology subsidiary has announced it will establish a major technology hub in Puerto Princesa City, with an expected investment of PHP 8 billion and the creation of 5,000 direct jobs over the next five years.</p>
    <p>The announcement was made during the Palawan Investment Summit, where PEZA (Philippine Economic Zone Authority) also unveiled tax incentives designed to attract more technology companies to the region.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=400&fit=crop",
    categoryId: 19,
    categoryName: "Technology",
    categorySlug: "technology",
    authorName: "Ana Bautista",
    authorAvatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: true,
    views: 6750,
    publishedAt: new Date("2024-03-08T14:00:00"),
    tags: ["Technology", "Jobs", "Economy", "Puerto Princesa", "City News"],
  },
  {
    id: 4,
    title: "Palawan Provincial Budget for 2024 Hits Record PHP 12 Billion",
    slug: "palawan-provincial-budget-2024-record-twelve-billion",
    excerpt: "The Palawan Sangguniang Panlalawigan has approved the largest provincial budget in history, with major allocations for infrastructure and social services.",
    content: `<p>The Palawan Sangguniang Panlalawigan has ratified the provincial government's record-breaking PHP 12.3 billion budget for fiscal year 2024, the largest in the province's history. The budget represents a 28% increase from 2023's PHP 9.6 billion allocation.</p>
    <p>Major spending priorities include infrastructure development at PHP 4.8 billion, health services at PHP 2.1 billion, education at PHP 1.9 billion, and environmental protection programs at PHP 1.2 billion.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=400&fit=crop",
    categoryId: 1,
    categoryName: "Provincial News",
    categorySlug: "provincial-news",
    authorName: "Roberto Cruz",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 4320,
    publishedAt: new Date("2024-03-07T09:00:00"),
    tags: ["Budget", "Government", "Palawan", "Politics", "Provincial News"],
  },
  {
    id: 5,
    title: "Palawan Pawnshop Group Posts 40% Profit Surge in Q4 2023",
    slug: "palawan-pawnshop-group-forty-percent-profit-surge-q4-2023",
    excerpt: "The Palawan Pawnshop Group continues its impressive growth trajectory, with Q4 2023 profits surging 40% year-over-year driven by digital financial services expansion.",
    content: `<p>Palawan Pawnshop Group Inc. has reported a 40% surge in net profit for the fourth quarter of 2023, reaching PHP 3.2 billion compared to PHP 2.3 billion in the same period last year. The strong performance was driven by rapid expansion in digital financial services and remittance operations.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&h=400&fit=crop",
    categoryId: 20,
    categoryName: "Business",
    categorySlug: "business",
    authorName: "Clara Mendoza",
    authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 3890,
    publishedAt: new Date("2024-03-06T11:00:00"),
    tags: ["Business", "Finance", "Economy"],
  },
  {
    id: 6,
    title: "Palawan Panthers Win PBA D-League Championship",
    slug: "palawan-panthers-pba-d-league-championship",
    excerpt: "The Palawan Panthers clinched the PBA D-League Championship in a thrilling seven-game series, bringing home the title to the island province.",
    content: `<p>The Palawan Panthers have captured the PBA D-League Foundation Cup championship, defeating the Makati Super Crunch in a grueling seven-game series that concluded with a dramatic 89-84 victory at the Ynares Center in Antipolo City.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800&h=400&fit=crop",
    categoryId: 21,
    categoryName: "Sports",
    categorySlug: "sports",
    authorName: "Miguel Torres",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 7210,
    publishedAt: new Date("2024-03-05T16:00:00"),
    tags: ["Basketball", "PBA", "Sports", "Palawan"],
  },
  {
    id: 7,
    title: "Coron Bay Coral Reef Restoration Project Exceeds Targets",
    slug: "coron-bay-coral-reef-restoration-exceeds-targets",
    excerpt: "A three-year coral reef restoration initiative in Coron Bay has exceeded its targets, with 85% of transplanted corals surviving.",
    content: `<p>The Coral Triangle Initiative's flagship project in Coron Bay has exceeded its three-year targets, with 85% survival rates for transplanted coral fragments — significantly higher than the 60% target originally set for the program.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=400&fit=crop",
    categoryId: 8,
    categoryName: "Environment",
    categorySlug: "environment",
    authorName: "Liza Garcia",
    authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 2840,
    publishedAt: new Date("2024-03-04T08:30:00"),
    tags: ["Environment", "Coron", "Marine", "Conservation"],
  },
  {
    id: 8,
    title: "El Nido Launches New Island-Hopping Rules to Protect Marine Life",
    slug: "el-nido-new-island-hopping-rules-marine-life",
    excerpt: "El Nido's local government has introduced new island-hopping regulations including time limits and sunscreen restrictions to protect the area's delicate marine ecosystem.",
    content: `<p>The Municipality of El Nido has announced a comprehensive set of new regulations for island-hopping tours, effective April 1, 2024. The rules include strict carrying capacity limits, a ban on chemical sunscreens, and mandatory time restrictions at sensitive marine sites.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800&h=400&fit=crop",
    categoryId: 18,
    categoryName: "Tourism",
    categorySlug: "tourism",
    authorName: "Maria Santos",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 5430,
    publishedAt: new Date("2024-03-03T13:00:00"),
    tags: ["El Nido", "Tourism", "Marine", "Environment"],
  },
  {
    id: 9,
    title: "Palawan State University Launches Campus Journalism Bootcamp",
    slug: "psu-campus-journalism-bootcamp",
    excerpt: "Student journalists from across Palawan gather in Puerto Princesa for an intensive training on fact-checking, digital storytelling, and ethical reporting.",
    content: `<p>More than 150 student journalists from senior high schools and universities across Palawan have joined the week-long <strong>Campus Journalism Bootcamp</strong> hosted by Palawan State University (PSU).</p>
    <p>The program features workshops on news writing, photojournalism, podcast production, and social media verification, led by editors and reporters from Palawan Daily News and partner newsrooms.</p>
    <h2>Training the Next Generation of Storytellers</h2>
    <p>According to organizers, the bootcamp aims to strengthen campus publications and equip young journalists with tools to fight misinformation while telling compelling local stories.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?w=800&h=400&fit=crop",
    categoryId: 17,
    categoryName: "Youth & Campus",
    categorySlug: "youth-campus",
    authorName: "Hanna Camella Talabucon",
    authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 1980,
    publishedAt: new Date("2024-03-02T10:15:00"),
    tags: ["Campus", "Education", "Journalism", "PSU"],
  },
  {
    id: 10,
    title: "Malacañang Backs Expanded Eco-Tourism Program for Palawan",
    slug: "palace-backs-expanded-eco-tourism-program-palawan",
    excerpt: "The Office of the President has endorsed a multi-agency eco‑tourism push that positions Palawan as a national model for sustainable island development.",
    content: `<p>Malacañang has thrown its full support behind a new <strong>National Eco‑Tourism Corridor</strong> program that places Palawan at the center of the country's long‑term strategy for sustainable tourism.</p>
    <p>In a Palace briefing, officials from the Department of Tourism, DENR, and NEDA highlighted Palawan's experience in managing protected areas and community‑based tourism as a blueprint for other island provinces.</p>
    <h2>National Spotlight on Local Initiatives</h2>
    <p>The initiative will channel national funding to expand waste management, renewable energy, and coastal protection projects in key Palawan destinations, while requiring stricter compliance with environmental laws.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&h=400&fit=crop",
    categoryId: 5,
    categoryName: "National News",
    categorySlug: "national",
    authorName: "Sevedeo Borda III",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 4120,
    publishedAt: new Date("2024-03-01T09:45:00"),
    tags: ["National", "Tourism", "Malacañang", "Palawan", "National News"],
  },
  {
    id: 11,
    title: "Senior High Students Launch Community Podcast in Barangay San Pedro",
    slug: "senior-high-students-community-podcast-san-pedro",
    excerpt: "A group of Grade 12 students turns a classroom project into a weekly podcast featuring youth voices on climate, education, and mental health.",
    content: `<p>What started as a performance task for media and information literacy has become a full‑fledged weekly podcast called <strong>“Barangay Youth Mic”</strong>, produced by senior high students in Barangay San Pedro, Puerto Princesa City.</p>
    <p>The show, recorded from a makeshift studio inside a classroom, tackles topics such as climate anxiety, study hacks, and stories of young volunteers working in coastal clean‑ups and literacy programs.</p>
    <h2>Local Stories, Youth Perspective</h2>
    <p>Teachers say the project has boosted students' confidence and digital skills, while barangay officials are exploring ways to air selected episodes on community radio.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&h=400&fit=crop",
    categoryId: 17,
    categoryName: "Youth & Campus",
    categorySlug: "youth-campus",
    authorName: "Hanna Camella Talabucon",
    authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 1560,
    publishedAt: new Date("2024-02-28T16:20:00"),
    tags: ["Youth", "Podcast", "Education", "Community"],
  },
  {
    id: 12,
    title: "How to Advertise with Palawan Daily News",
    slug: "how-to-advertise-with-pdn",
    excerpt: "Reach thousands of engaged readers across Palawan. Explore our diverse advertising options from digital banners to sponsored content.",
    content: `<p>Palawan Daily News offers a variety of advertising solutions tailored to meet your business needs. Whether you are looking to increase brand awareness or drive conversions, our platform provides the perfect environment to reach your target audience.</p>
    <h2>Our Audience</h2>
    <p>Our readers are primarily based in Palawan, consisting of professionals, government officials, and community leaders who stay informed with our trusted reporting.</p>
    <h2>Advertising Options</h2>
    <ul>
      <li><strong>Display Ads:</strong> High-impact banner placements on our homepage and article pages.</li>
      <li><strong>Sponsored Content:</strong> Tell your story through professionally written articles that resonate with our readers.</li>
      <li><strong>Social Media Promotion:</strong> Leverage our strong social media presence to amplify your message.</li>
    </ul>
    <p>For more information on our rates and packages, please contact our sales team at <a href="mailto:ads@palawandailynews.com">ads@palawandailynews.com</a>.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&h=400&fit=crop",
    categoryId: 12,
    categoryName: "Advertise",
    categorySlug: "advertise",
    authorName: "PDN Sales Team",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 1200,
    publishedAt: new Date("2024-03-15T09:00:00"),
    tags: ["Advertise", "Business", "Marketing"],
  },
  {
    id: 13,
    title: "The Importance of Local Media in the Digital Age",
    slug: "importance-of-local-media-digital-age",
    excerpt: "In an era of global information, the role of local news remains more critical than ever for community empowerment and accountability.",
    content: `<p>As we navigate an increasingly crowded digital landscape, the value of reliable local journalism cannot be overstated. Local media serves as the backbone of our community, providing the oversight and information that national outlets often miss.</p>
    <p>At Palawan Daily News, we believe that staying informed about your own backyard is the first step toward active citizenship.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1495020689067-958852a7765e?w=800&h=400&fit=crop",
    categoryId: 10,
    categoryName: "Opinion",
    categorySlug: "opinion",
    authorName: "Harthwell Capistrano",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 850,
    publishedAt: new Date("2024-03-14T15:00:00"),
    tags: ["Opinion", "Journalism", "Community"],
  },
  {
    id: 14,
    title: "Public Notice: Upcoming Coastal Zone Management Hearing",
    slug: "public-notice-coastal-zone-management-hearing",
    excerpt: "The Provincial Government announces a public hearing regarding the proposed revisions to the Coastal Zone Management Plan.",
    content: `<p>Notice is hereby given to the public that the Provincial Government of Palawan will hold a public hearing to discuss the proposed amendments to the 10-year Coastal Zone Management Plan.</p>
    <p>The hearing aims to gather input from stakeholders, including fisherfolk, tourism operators, and environmental groups, to ensure a balanced approach to coastal development and conservation.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&h=400&fit=crop",
    categoryId: 11,
    categoryName: "Legal Section",
    categorySlug: "legal",
    authorName: "Legal Desk",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 450,
    publishedAt: new Date("2024-03-13T10:00:00"),
    tags: ["Legal", "Public Notice", "Palawan"],
  },
  {
    id: 15,
    title: "5 Hidden Gems to Visit in Palawan This Summer",
    slug: "5-hidden-gems-palawan-summer",
    excerpt: "Beyond El Nido and Coron, explore these lesser-known destinations that offer breathtaking views and serene retreats.",
    content: `<p>Summer is just around the corner, and while El Nido and Coron remain favorites, Palawan has so much more to offer for those willing to venture off the beaten path.</p>
    <p>From the white sands of Balabac to the waterfalls of Quezon, here are five hidden gems you should add to your travel list this year.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800&h=400&fit=crop",
    categoryId: 11,
    categoryName: "Lifestyle",
    categorySlug: "lifestyle",
    authorName: "Clarina Herrera Guludah",
    authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 3200,
    publishedAt: new Date("2024-03-12T14:00:00"),
    tags: ["Lifestyle", "Travel", "Palawan", "Summer"],
  },
  {
    id: 16,
    title: "Global Leaders Converge for Climate Action Summit in Geneva",
    slug: "global-leaders-climate-action-summit-geneva",
    excerpt: "World leaders and environmental experts meet in Geneva to discuss urgent measures to combat climate change and accelerate renewable energy transitions.",
    content: `<p>The United Nations Climate Action Summit opened today in Geneva, bringing together heads of state, industry leaders, and climate scientists to address the accelerating pace of global warming.</p>
    <p>The summit aims to finalize international agreements on carbon emission reductions and establish a multibillion-dollar fund to assist developing nations in their transition to green energy.</p>
    <h2>Urgent Measures Required</h2>
    <p>In his opening address, the UN Secretary-General emphasized that 'the era of global boiling has arrived' and called for immediate, large-scale interventions across all economic sectors.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=400&fit=crop",
    categoryId: 14,
    categoryName: "International News",
    categorySlug: "international",
    authorName: "Staff Reporter",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 5670,
    publishedAt: new Date("2024-03-18T10:00:00"),
    tags: ["International", "Climate Change", "UN", "World"],
  },
  {
    id: 17,
    title: "Major Breakthrough in Quantum Computing Research Announced",
    slug: "quantum-computing-breakthrough-research",
    excerpt: "A team of international scientists has achieved a significant milestone in quantum error correction, paving the way for more stable and powerful quantum processors.",
    content: `<p>Researchers from a global consortium of universities have announced a major breakthrough in the field of quantum computing, successfully demonstrating a new method for correcting quantum errors that significantly increases the stability of quantum bits (qubits).</p>
    <p>This development is seen as a critical step toward the realization of practical, large-scale quantum computers that could revolutionize fields ranging from cryptography to drug discovery.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=400&fit=crop",
    categoryId: 14,
    categoryName: "International News",
    categorySlug: "international",
    authorName: "Staff Reporter",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 3420,
    publishedAt: new Date("2024-03-17T15:30:00"),
    tags: ["International", "Technology", "Science", "Quantum Computing"],
  },
  {
    id: 18,
    title: "The Importance of Digital Literacy in Modern Palawan",
    slug: "importance-digital-literacy-palawan",
    excerpt: "Editorial: As Palawan embraces digital transformation, ensuring all citizens have the skills to navigate the internet safely is paramount.",
    content: `<p>In an increasingly connected world, Palawan cannot afford to be left behind. Digital literacy is no longer a luxury; it is a fundamental skill required for participation in modern society.</p>
    <p>From online banking to accessing government services, our province is moving toward a digital-first future. We must ensure that our educational systems and community programs are equipped to bridge the digital divide.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=400&fit=crop",
    categoryId: 15,
    categoryName: "Editorial",
    categorySlug: "editorial",
    authorName: "The Editorial Board",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 1200,
    publishedAt: new Date("2024-03-19T08:00:00"),
    tags: ["Editorial", "Digital Literacy", "Palawan", "Future"],
  },
  {
    id: 19,
    title: "Palawan State University Students Win National Robotics Competition",
    slug: "psu-students-national-robotics-win",
    excerpt: "Engineering students from PSU brought home the top prize in the 2024 National Robotics Challenge held in Manila last week.",
    content: `<p>A team of engineering students from Palawan State University (PSU) has made the province proud by winning the grand prize at the 2024 National Robotics Challenge.</p>
    <p>The team's project, an autonomous underwater drone designed for coral reef monitoring, was praised by judges for its innovation and practical application in marine conservation.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=400&fit=crop",
    categoryId: 17,
    categoryName: "Youth & Campus",
    categorySlug: "youth-campus",
    authorName: "Maria Santos",
    authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 4500,
    publishedAt: new Date("2024-03-16T09:00:00"),
    tags: ["Youth", "Campus", "PSU", "Robotics"],
  },
  {
    id: 20,
    title: "Preserving Palawan's Natural Beauty for the Next Generation",
    slug: "preserving-palawan-nature-editorial",
    excerpt: "Editorial: Sustainable tourism is the only path forward if we want our children to enjoy the same pristine waters and forests we have today.",
    content: `<p>Palawan is often called the 'Last Frontier.' But as tourism numbers continue to grow, the pressure on our natural environment is becoming unsustainable.</p>
    <p>We must take bold steps now to implement stricter environmental regulations and promote eco-friendly travel practices. Our economic growth should not come at the cost of our ecological heritage.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=400&fit=crop",
    categoryId: 15,
    categoryName: "Editorial",
    categorySlug: "editorial",
    authorName: "The Editorial Board",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 2100,
    publishedAt: new Date("2024-03-15T11:00:00"),
    tags: ["Editorial", "Environment", "Tourism", "Sustainability"],
  },
  {
    id: 21,
    title: "City Government to Revitalize Puerto Princesa Baywalk",
    slug: "city-government-revitalize-baywalk",
    excerpt: "A PHP 150-million redevelopment plan has been unveiled to transform the iconic Baywalk into a world-class leisure and cultural hub.",
    content: `<p>The City Government of Puerto Princesa has officially unveiled its master plan for the revitalization of the Baywalk, aiming to boost local tourism and provide better recreational spaces for residents.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=800&h=400&fit=crop",
    categoryId: 2,
    categoryName: "City News",
    categorySlug: "city-news",
    authorName: "Roberto Cruz",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 3100,
    publishedAt: new Date("2024-03-20T10:00:00"),
    tags: ["City News", "Puerto Princesa", "Tourism", "Infrastructure"],
  },
  {
    id: 22,
    title: "New District Hospital Opens in Southern Palawan",
    slug: "new-district-hospital-southern-palawan",
    excerpt: "The 100-bed facility in Brooke's Point is expected to significantly improve healthcare accessibility for thousands of residents in the province's southern towns.",
    content: `<p>Residents of southern Palawan now have access to better healthcare services with the official opening of the new district hospital in Brooke's Point.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&h=400&fit=crop",
    categoryId: 1,
    categoryName: "Provincial News",
    categorySlug: "provincial-news",
    authorName: "Liza Garcia",
    authorAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 2500,
    publishedAt: new Date("2024-03-21T09:00:00"),
    tags: ["Provincial News", "Healthcare", "Health", "Palawan"],
  },
  {
    id: 23,
    title: "MIMAROPA Unity Games Set to Kick Off in Puerto Princesa",
    slug: "mimaropa-unity-games-puerto-princesa",
    excerpt: "Athletes from across the five provinces of the MIMAROPA region will gather for a week of sporting competition and cultural exchange.",
    content: `<p>The City of Puerto Princesa is all set to host the MIMAROPA Unity Games, bringing together thousands of athletes and officials from Oriental Mindoro, Occidental Mindoro, Marinduque, Romblon, and Palawan.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1541252260730-0412e8e2108e?w=800&h=400&fit=crop",
    categoryId: 16, // Regional context
    categoryName: "Regional News",
    categorySlug: "regional-news",
    authorName: "Miguel Torres",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 1800,
    publishedAt: new Date("2024-03-22T08:00:00"),
    tags: ["Regional News", "MIMAROPA", "Sports", "Unity"],
  },
  {
    id: 24,
    title: "Department of Energy Unveils New Renewable Energy Policy",
    slug: "doe-new-renewable-energy-policy",
    excerpt: "The new policy framework aims to accelerate the transition to clean energy by providing more incentives for solar and wind projects across the country.",
    content: `<p>The Department of Energy (DOE) has introduced a landmark policy framework designed to significantly speed up the Philippines' transition to renewable energy sources.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&h=400&fit=crop",
    categoryId: 5,
    categoryName: "National News",
    categorySlug: "national",
    authorName: "Ana Bautista",
    authorAvatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 4200,
    publishedAt: new Date("2024-03-23T11:00:00"),
    tags: ["National", "Energy", "Renewable", "Policy"],
  },
  {
    id: 25,
    title: "Global Economic Forecast Predicts Moderate Growth in 2024",
    slug: "global-economic-forecast-2024",
    excerpt: "International economists suggest that while challenges remain, the global economy is on a path to stabilization and moderate growth this year.",
    content: `<p>A new report from the International Economic Forum suggests a cautiously optimistic outlook for the global economy in 2024, with growth projected at 3.1%.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&h=400&fit=crop",
    categoryId: 14,
    categoryName: "International News",
    categorySlug: "international",
    authorName: "Staff Reporter",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 5120,
    publishedAt: new Date("2024-03-24T14:00:00"),
    tags: ["International", "Economy", "Finance", "Global"],
  },
  {
    id: 26,
    title: "Student-Led Reforestation Project Plants 10,000 Trees",
    slug: "student-led-reforestation-ten-thousand-trees",
    excerpt: "A coalition of student organizations in Palawan has successfully completed its first major reforestation drive, planting native trees in critical watersheds.",
    content: `<p>In a powerful display of environmental leadership, students from various universities in Palawan have successfully planted 10,000 native tree saplings in the Irawan Watershed.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&h=400&fit=crop",
    categoryId: 17,
    categoryName: "Youth & Campus",
    categorySlug: "youth-campus",
    authorName: "Hanna Camella Talabucon",
    authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 2900,
    publishedAt: new Date("2024-03-25T16:00:00"),
    tags: ["Youth", "Environment", "Reforestation", "Campus"],
  },
  {
    id: 27,
    title: "The Vital Role of Transparency in Local Governance",
    slug: "vital-role-transparency-local-governance",
    excerpt: "Editorial: Open access to information is not just a right but a necessity for building trust and ensuring ethical leadership in our province.",
    content: `<p>Transparency is the lifeblood of a healthy democracy. At the local level, where government decisions directly impact the daily lives of citizens, it is paramount.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=400&fit=crop",
    categoryId: 15,
    categoryName: "Editorial",
    categorySlug: "editorial",
    authorName: "The Editorial Board",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 1400,
    publishedAt: new Date("2024-03-26T08:00:00"),
    tags: ["Editorial", "Transparency", "Government", "Ethics"],
  },
  {
    id: 28,
    title: "Why Community Gardening is the Future of Urban Sustainability",
    slug: "why-community-gardening-matters",
    excerpt: "Opinion: Beyond providing fresh produce, community gardens foster social bonds and resilience in our growing city.",
    content: `<p>Urban living can often feel disconnected from nature and community. Community gardens offer a powerful solution to both problems.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800&h=400&fit=crop",
    categoryId: 10,
    categoryName: "Opinion",
    categorySlug: "opinion",
    authorName: "Jose Reyes",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 980,
    publishedAt: new Date("2024-03-27T09:00:00"),
    tags: ["Opinion", "Sustainability", "Community", "Urban Farming"],
  },
  {
    id: 29,
    title: "Palawan Records Zero New Dengue Cases in Q1 2024",
    slug: "palawan-zero-dengue-cases-q1-2024",
    excerpt: "Health officials credit the successful 'Anti-Dengue Drive' and community cooperation for the significant drop in mosquito-borne illnesses.",
    content: `<p>The Provincial Health Office has announced a major public health milestone, recording zero new dengue cases across Palawan for the first quarter of 2024.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&h=400&fit=crop",
    categoryId: 1,
    categoryName: "Provincial News",
    categorySlug: "provincial-news",
    authorName: "Maria Santos",
    authorAvatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 3300,
    publishedAt: new Date("2024-03-28T10:00:00"),
    tags: ["Provincial News", "Health", "Palawan", "Dengue"],
  },
  {
    id: 30,
    title: "Puerto Princesa City to Host International Coastal Clean-up 2024",
    slug: "puerto-princesa-international-coastal-cleanup",
    excerpt: "The city government expects over 5,000 volunteers to join the largest environmental event of the year along the Puerto Princesa coastline.",
    content: `<p>Puerto Princesa City is gearing up for the 2024 International Coastal Clean-up, targeting key coastal areas in the city proper and surrounding barangays.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1618477388954-7852f32655ec?w=800&h=400&fit=crop",
    categoryId: 2,
    categoryName: "City News",
    categorySlug: "city-news",
    authorName: "Roberto Cruz",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 1200,
    publishedAt: new Date("2024-03-29T09:00:00"),
    tags: ["City News", "Environment", "Puerto Princesa", "Clean-up"],
  },
  {
    id: 31,
    title: "New Public Market Terminal Set for Completion in June",
    slug: "new-public-market-terminal-completion",
    excerpt: "The city's engineering department reports 85% progress on the high-tech transportation hub designed to decongest city traffic.",
    content: `<p>Commuters and vendors in Puerto Princesa can look forward to a more organized and modern public market terminal, with the project slated for a grand opening this June.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800&h=400&fit=crop",
    categoryId: 2,
    categoryName: "City News",
    categorySlug: "city-news",
    authorName: "Maria Santos",
    authorAvatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 2400,
    publishedAt: new Date("2024-03-30T08:30:00"),
    tags: ["City News", "Infrastructure", "Puerto Princesa", "Traffic"],
  },
  {
    id: 32,
    title: "MIMAROPA Agriculture Summit Focuses on Food Security",
    slug: "mimaropa-agriculture-summit-food-security",
    excerpt: "Leaders from Mindoro, Marinduque, Romblon, and Palawan meet to discuss regional strategies for climate-resilient farming.",
    content: `<p>The inaugural MIMAROPA Agriculture Summit opened today in Calapan City, with a strong focus on ensuring food security across the region's island provinces.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=800&h=400&fit=crop",
    categoryId: 16,
    categoryName: "Regional News",
    categorySlug: "regional-news",
    authorName: "Liza Garcia",
    authorAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 3100,
    publishedAt: new Date("2024-03-31T10:00:00"),
    tags: ["Regional News", "MIMAROPA", "Agriculture", "Food Security"],
  },
  {
    id: 33,
    title: "Regional Health Offices Braced for Summer Disease Surge",
    slug: "regional-health-surge-summer",
    excerpt: "The Department of Health in MIMAROPA has issued a regional advisory to all provincial health offices regarding heat-related illnesses.",
    content: `<p>MIMAROPA regional health officials are increasing surveillance and public awareness campaigns as temperatures begin to rise ahead of the summer season.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=800&h=400&fit=crop",
    categoryId: 16,
    categoryName: "Regional News",
    categorySlug: "regional-news",
    authorName: "Miguel Torres",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 1900,
    publishedAt: new Date("2024-04-01T07:45:00"),
    tags: ["Regional News", "MIMAROPA", "Health", "Summer"],
  },
  {
    id: 34,
    title: "PBBM Signs New Infrastructure Growth Act",
    slug: "pbbm-signs-infrastructure-growth-act",
    excerpt: "The new law prioritizes high-impact transportation and energy projects in provincial regions to stimulate national economic growth.",
    content: `<p>President Ferdinand "Bongbong" Marcos Jr. has signed into law the Infrastructure Growth Act, marking a major milestone in the administration's 'Build Better More' program.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=400&fit=crop",
    categoryId: 5,
    categoryName: "National News",
    categorySlug: "national",
    authorName: "Staff Reporter",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 5600,
    publishedAt: new Date("2024-04-02T11:00:00"),
    tags: ["National News", "Government", "Infrastructure", "Policy"],
  },
  {
    id: 35,
    title: "The Digital Frontier: Empowering Rural Palawan",
    slug: "digital-frontier-empowering-rural-palawan",
    excerpt: "Opinion: Connecting our remote island communities to the internet is about more than technology; it's about equality and opportunity.",
    content: `<p>As we celebrate the technological leaps in our provincial capital, we must not forget the thousands of Palaweños living in areas still untouched by a reliable digital signal.</p>`,
    featuredImage: "https://images.unsplash.com/photo-1516321497487-e288fb19713f?w=800&h=400&fit=crop",
    categoryId: 10,
    categoryName: "Opinion",
    categorySlug: "opinion",
    authorName: "Jose Reyes",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    status: "published",
    featured: false,
    breaking: false,
    views: 1100,
    publishedAt: new Date("2024-04-03T15:00:00"),
    tags: ["Opinion", "Digital Divide", "Palawan", "Future"],
  },
];

export type MockArticle = (typeof mockArticles)[0];
export type MockCategory = (typeof mockCategories)[0];

export interface Advertisement {
  id: string;
  type: 'billboard' | 'leaderboard' | 'sidebar' | 'header';
  fit: 'cover' | 'contain';
  imageUrl?: string;
  linkUrl?: string;
  active: boolean;
  label: string;
  sublabel: string;
}

export const mockAds: Advertisement[] = [
  {
    id: "home-billboard",
    type: "billboard",
    fit: "cover",
    active: false,
    label: "BILLBOARD ADVERTISEMENT SPACE",
    sublabel: "Get your brand in front of thousands of daily readers",
  },
  {
    id: "home-leaderboard",
    type: "leaderboard",
    fit: "cover",
    active: false,
    label: "LEADERBOARD ADVERTISEMENT SPACE",
    sublabel: "Contact us at ads@palawandaily.com for rates",
  },
  {
    id: "article-sidebar",
    type: "sidebar",
    fit: "cover",
    active: false,
    label: "SIDEBAR ADVERTISEMENT SPACE",
    sublabel: "Contact us at ads@palawandaily.com for rates",
  },
  {
    id: "home-header",
    type: "header",
    fit: "cover",
    active: true,
    label: "Be a certified safety officer",
    sublabel: "Attend our online and face-to-face training.",
  },
];

export interface PdnContactInfo {
  officeName: string;
  addressLines: string[];
  email: string;
  telephone?: string;
  mobile?: string;
  businessHours: string[];
}

export const mockPdnContactInfo: PdnContactInfo = {
  officeName: "Palawan Daily News Head Office",
  addressLines: [
    "3/F Daniel Alley Bldg. II",
    "National Highway, San Pedro",
    "Puerto Princesa City 5300",
    "Philippines",
  ],
  email: "info@palawandailynews.com",
  telephone: "+63 (48) 717 0288",
  mobile: "+63 917 829 1370",
  businessHours: [
    "Monday–Friday: 8:30 AM – 5:30 PM",
    "Saturday: 9:00 AM – 12:00 PM",
    "Sunday: Closed",
  ],
};

export interface PdnOwnershipFundingInfo {
  title: string;
  highlights: string[];
  bodyHtml: string;
}

export type OrgChartDepartment =
  | "management"
  | "news"
  | "creatives"
  | "online-radio"
  | "digital"
  | "online-tv"
  | "columnists";

export interface OrgChartEmployee {
  id: string;
  name: string;
  title: string;
  department: OrgChartDepartment;
  avatarUrl?: string | null;
  facebookUrl?: string | null;
}

export const mockOrgChartDepartments: { slug: OrgChartDepartment; label: string }[] = [
  { slug: "management", label: "Management" },
  { slug: "news", label: "News Department" },
  { slug: "creatives", label: "Creatives (Audio Video Animation) Team" },
  { slug: "online-radio", label: "Online Radio Team" },
  { slug: "digital", label: "Digital (Web & SocMed)" },
  { slug: "online-tv", label: "Online TV" },
];

export const mockOrgChartEmployees: OrgChartEmployee[] = [
  { id: "1", name: "Kent Janaban", title: "Publisher", department: "management", avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face", facebookUrl: "#" },
  { id: "2", name: "Harthwell Capistrano", title: "Editor in Chief / Co-founder", department: "management", avatarUrl: null, facebookUrl: "#" },
  { id: "3", name: "Clarina Herrera Guludah", title: "Broadcast Journalist / Co-founder", department: "management", avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face", facebookUrl: "#" },
  { id: "4", name: "Rexcel John Sorza", title: "Editorial Consultant", department: "management", avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face", facebookUrl: "#" },
  { id: "5", name: "Atty. Analisa Navarro - Padon", title: "Legal Counsel", department: "management", avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face", facebookUrl: "#" },
  { id: "6", name: "Sevedeo Borda III", title: "Managing Editor", department: "news", avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face", facebookUrl: "#" },
  { id: "7", name: "Hanna Camella Talabucon", title: "Associate Editor", department: "news", avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face", facebookUrl: "#" },
  { id: "8", name: "Gerardo Reyes Jr.", title: "Journalist", department: "news", avatarUrl: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=200&h=200&fit=crop&crop=face", facebookUrl: "#" },
  { id: "9", name: "John Castor Viernes", title: "Sales & Marketing / Journalist", department: "news", avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face", facebookUrl: "#" },
  { id: "10", name: "Maria Santos", title: "Senior Journalist", department: "news", avatarUrl: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&h=200&fit=crop&crop=face", facebookUrl: "#" },
  { id: "11", name: "Mechael Glen Dagot", title: "Circulation Officer", department: "digital", avatarUrl: null, facebookUrl: "#" },
  { id: "12", name: "Carlos dela Cruz", title: "Digital Content Manager", department: "digital", avatarUrl: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=200&h=200&fit=crop&crop=face", facebookUrl: "#" },
  { id: "13", name: "Ana Bautista", title: "Social Media Editor", department: "digital", avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face", facebookUrl: "#" },
  { id: "14", name: "Roberto Cruz", title: "Online Radio Host", department: "online-radio", avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face", facebookUrl: "#" },
  { id: "15", name: "Liza Garcia", title: "Online Radio Producer", department: "online-radio", avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop&crop=face", facebookUrl: "#" },
  { id: "16", name: "Miguel Torres", title: "Video Producer", department: "creatives", avatarUrl: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=200&h=200&fit=crop&crop=face", facebookUrl: "#" },
  { id: "17", name: "Sofia Reyes", title: "Motion Designer", department: "creatives", avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=face", facebookUrl: "#" },
  { id: "18", name: "Jose Reyes", title: "Online TV Anchor", department: "online-tv", avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face", facebookUrl: "#" },
];

export const mockPdnOwnershipFundingInfo: PdnOwnershipFundingInfo = {
  title: "Ownership and Funding Information",
  highlights: [
    "Palawan Daily News is independently owned and operated.",
    "We do not accept funding that influences editorial decision-making.",
    "Revenue primarily comes from advertising and other self-sustaining sources.",
  ],
  bodyHtml: `
    <p><strong>Palawan Daily News</strong> is a regional media platform based in Puerto Princesa City, Palawan. For this demo project, the details below are intentionally written as <em>dummy reference content</em> so you can adjust it later to match your official company disclosures.</p>
    <p>The publication is <strong>self-funded</strong> and has operated continuously since 2018 with a commitment to accuracy, fairness, and balance. We maintain a clear separation between our newsroom and revenue operations.</p>
    <p>Majority of the organization’s operating income is generated through:</p>
    <ul>
      <li>Display and sponsored advertising placements</li>
      <li>Brand partnerships and event coverage packages</li>
      <li>Content production services (when clearly labeled and contracted)</li>
    </ul>
    <p>We publish online and may expand into additional formats (print, radio, video) depending on community demand and sustainability goals.</p>
    <p>If you have questions about ownership, funding, or corrections, please contact us using the information on the <a href="/about/contact-us">Contact Us</a> page.</p>
  `,
};
